# Generated by Django 6.1.1 on 2026-09-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
