# Generated by Django 6.1.1 on 2026-09-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_autoridad_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoridad',
            options={'verbose_name_plural': 'Autoridades'},
        ),
        migrations.AlterModelOptions(
            name='delegacion',
            options={'verbose_name_plural': 'Delegaciones'},
        ),
        migrations.AddField(
            model_name='delegacion',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='delegacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoridades', to='institucion.delegacion'),
        ),
    ]
